/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSupportRouteImport } from './routes/dashboard.support'
import { Route as DashboardSavedRouteImport } from './routes/dashboard.saved'
import { Route as DashboardPlanRouteImport } from './routes/dashboard.plan'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as DashboardLettersIdRouteImport } from './routes/dashboard.letters.$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSavedRoute = DashboardSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlanRoute = DashboardPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLettersIdRoute = DashboardLettersIdRouteImport.update({
  id: '/letters/$id',
  path: '/letters/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/dashboard/plan': typeof DashboardPlanRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/letters/$id': typeof DashboardLettersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/upload': typeof ApiUploadRoute
  '/dashboard/plan': typeof DashboardPlanRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/letters/$id': typeof DashboardLettersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/dashboard/plan': typeof DashboardPlanRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/letters/$id': typeof DashboardLettersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/upload'
    | '/dashboard/plan'
    | '/dashboard/saved'
    | '/dashboard/support'
    | '/dashboard/'
    | '/dashboard/letters/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/upload'
    | '/dashboard/plan'
    | '/dashboard/saved'
    | '/dashboard/support'
    | '/dashboard'
    | '/dashboard/letters/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/upload'
    | '/dashboard/plan'
    | '/dashboard/saved'
    | '/dashboard/support'
    | '/dashboard/'
    | '/dashboard/letters/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiUploadRoute: typeof ApiUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/saved': {
      id: '/dashboard/saved'
      path: '/saved'
      fullPath: '/dashboard/saved'
      preLoaderRoute: typeof DashboardSavedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/plan': {
      id: '/dashboard/plan'
      path: '/plan'
      fullPath: '/dashboard/plan'
      preLoaderRoute: typeof DashboardPlanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/letters/$id': {
      id: '/dashboard/letters/$id'
      path: '/letters/$id'
      fullPath: '/dashboard/letters/$id'
      preLoaderRoute: typeof DashboardLettersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardPlanRoute: typeof DashboardPlanRoute
  DashboardSavedRoute: typeof DashboardSavedRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardLettersIdRoute: typeof DashboardLettersIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardPlanRoute: DashboardPlanRoute,
  DashboardSavedRoute: DashboardSavedRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardLettersIdRoute: DashboardLettersIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ApiUploadRoute: ApiUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
